CREATE TABLE IF NOT EXISTS products (
id INTEGER PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(100) NOT NULL ,
description VARCHAR(255) NOT NULL ,
quantity INTEGER NOT NULL CHECK (quantity >=0) DEFAULT 0,
price INTEGER NOT NULL CHECK (price >=0) DEFAULT 0
);